### ISSUE TITLE
RuntimeError on nest_asyncio.apply() (There is no current event loop in thread 'Thread-3' )

### ISSUE THREAD

**Issue by eugeniashurko** [BlueBrain/nexus-forge#60]
Hi,

I have encountered an issue when initializing `KnowledgeGraphForge` on my local `Flask` server using
```
forge = KnowledgeGraphForge(forge_config_path, token=token)
```

This line produces the following traceback:

```
Traceback (most recent call last):
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/oshurko/Workspace/BlueBrainEmbedder/app.py", line 66, in fit_model
    forge_config_path, token=token)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/core/forge.py", line 171, in __init__
    self._model: Model = model(**model_config)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/specializations/models/rdf_model.py", line 69, in __init__
    super().__init__(source, **source_config)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/core/archetypes/model.py", line 47, in __init__
    self.service: Any = self._initialize_service(self.source, **source_config)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/core/archetypes/model.py", line 184, in _initialize_service
    return self._service_from_store(store, context_config, **source_config)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/specializations/models/rdf_model.py", line 144, in _service_from_store
    default_store: Store = store(endpoint, bucket, token)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/specializations/stores/bluebrain_nexus.py", line 84, in __init__
    model_context)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/core/archetypes/store.py", line 58, in __init__
    self.service: Any = self._initialize_service(self.endpoint, self.bucket, self.token)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/specializations/stores/bluebrain_nexus.py", line 433, in _initialize_service
    return Service(endpoint, self.organisation, self.project, token, self.model_context, 200)
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/kgforge/specializations/stores/nexus/service.py", line 93, in __init__
    nest_asyncio.apply()
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/site-packages/nest_asyncio.py", line 10, in apply
    loop = loop or asyncio.get_event_loop()
  File "/Users/oshurko/opt/anaconda3/envs/bbembed/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-3'.
```

In case it may give some insight on what is going on: in the source code the problematic line (`nest_asyncio.apply()`) is commented as '# This async to work on jupyter notebooks'

**Comment by eugeniashurko** [comment]
UPD: could fix it for Flask by commenting the problematic line. Tested in Jupyter notebook and we get the following (I guess which is why `nest_asyncio` was needed): 

```
Couldn't fetch 'SubCellularModel'
<action> run
<error> RuntimeError: asyncio.run() cannot be called from a running event loop
```

**Comment by MFSY** [comment]
Fixed in https://github.com/BlueBrain/nexus-forge/pull/62
